[build]
  command = "npm --prefix client install --legacy-peer-deps && npm --prefix client run build"
  publish = "client/dist"
  functions = "netlify/functions"

# ADD THIS SECTION BELOW
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg"]

[[plugins]]
package = "@netlify/plugin-csp-nonce"
  [plugins.inputs]
  reportOnly = false
  unsafeEval = false

# Content Security Policy (SCP)
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; base-uri 'self'; script-src 'strict-dynamic' https: http:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com https://cdn.jsdelivr.net; img-src 'self' https://www.netlify.com data:; connect-src 'self' https://khmer-calendar.netlify.app; report-uri /.netlify/functions/__csp-violations;frame-ancestors 'none';"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

# 1. Specific rule for the IP lookup (Bypasses AdBlockers)
[[redirects]]
  from = "/api/get-location"
  to = "https://ipapi.co/json/"
  status = 200
  force = true

# 2. Specific rule for the IP lookup (Bypasses AdBlockers)
[[redirects]]
  from = "/api/get-ip"
  to = "https://api.ipify.org?format=json"
  status = 200
  force = true

# backend 3. Your existing wildcard rule for other functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
 
# fallback for SPA 
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [dev]
  port = 8888
  publish = "public"
