[build]
  command = "npm install --legacy-peer-deps && npm --prefix client install --legacy-peer-deps && npm --prefix client run build"
  publish = "client/dist"
  functions = "netlify/functions"

# backend
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# fallback for SPA 
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200