CREATE TABLE holidays (
  id SERIAL PRIMARY KEY,
  desc VARCHAR(255) NOT NULL,
  day DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

